### ISSUE TITLE
hello do you still care about this project

### ISSUE THREAD

**Issue by camila314** [gdext/geode-app#1]
i wanna use the term geode for a gd mod related thing but i dont want to steal from an active project

**Comment by azureitte** [comment]
bruh...

**Comment by camila314** [comment]
so yes or no (we already asked the other guy iliashdz and they said yeah but i want permission from both people)

**Comment by iliasHDZ** [comment]
this hasn't been worked on in some time so go ahead.

**Comment by camila314** [comment]
ty 🙏🙏🙏🙏🙏
